### ISSUE TITLE
Make grunt task `stop_mockserver` synchronous for every port

### ISSUE THREAD

**Issue by josejulio** [jamesdbloom/mockserver-node#5]
I have my gruntfile setup like this:

```js
grunt.registerTask('default', [
    'jshint',
    'stop_mockserver',
    'start_mockserver',
    'run:kialimock',
    'watch'
  ]);
```
and my `watch` like this:
```js
watch: {
      gruntfile: {
        files: '<%= jshint.gruntfile.src %>',
        tasks: ['jshint:gruntfile']
      },
      lib: {
        files: '<%= jshint.lib.src %>',
        tasks: [
          'stop_mockserver',
          'jshint:lib',
          'start_mockserver',
          'run:kialimock'
        ]
      },
    },
```

So i want that every time a lib is changed, stop and start the mockserver, but it seems to me that the stop_mockserver doesn't wait for the server to stop and i get the following error:

```
Running "watch" task
Waiting...

Running "start_mockserver" task
Skipping {"host":"oss.sonatype.org","path":"/content/repositories/releases/org/mock-server/mockserver-netty/5.3.0/mockserver-netty-5.3.0-jar-with-dependencies.jar","port":443} as file already downloaded
Exception in thread "MockServer thread for port: 1090" Exception in thread "main" java.lang.RuntimeException: Exception while binding MockServer to port 1090
        at org.mockserver.lifecycle.LifeCycle$1.run(LifeCycle.java:102)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
java.lang.RuntimeException: Exception while binding MockServer to port 1090
        at org.mockserver.lifecycle.LifeCycle.bindToPorts(LifeCycle.java:109)
        at org.mockserver.proxy.http.HttpProxy.<init>(HttpProxy.java:48)
        at org.mockserver.proxy.ProxyBuilder.build(ProxyBuilder.java:54)
        at org.mockserver.cli.Main.main(Main.java:109)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

Running "run:kialimock" (run) task
Finished reconfiguration the mock server
```

**Comment by josejulio** [comment]
It seems that is actually waiting but only on one port, so if i use proxyPort and serverPort, it will only wait for serverPort.

https://github.com/jamesdbloom/mockserver-node/blob/master/index.js#L256

**Comment by jamesdbloom** [comment]
This issue should now be resolved because only a single port is exposed.  Both proxying and expectations are now handled through a single port.
